name: "Diploma Example Addon"
version: "0.1.0"
slug: "diploma_example"
description: "Base addon for diploma project"
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:home-automation
panel_title: "Diploma Addon"
homeassistant_api: true
hassio_api: true
arch:
  - amd64
options:
  log_level: info
schema:
  log_level: list(info|debug)
ports:
  8080/tcp: 8080
webui: "http://[HOST]:[PORT:8080]"
