name: "Adaptive Home Automations addon"
version: "0.1.20"
slug: "adaptive_home_automations_addon"
description: "Adaptive Home Automations addon for diploma project"
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:home-automation
panel_title: "Adaptive Home Automations"
homeassistant_api: true
hassio_api: true
arch:
  - amd64
options:
  log_level: info
  min_support: 5
  min_confidence: 0.6
  history_days: 7
  train_hour: 3
schema:
  log_level: list(info|debug)
  min_support: int(1,100)
  min_confidence: float(0.0,1.0)
  history_days: int(1,365)
  train_hour: int(0,23)
ports:
  8080/tcp: 8080
webui: "http://[HOST]:[PORT:8080]"
